/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pilacolalista;

import javax.swing.DefaultListModel;

public class frmCola extends javax.swing.JInternalFrame {

    String Cola[] = new String[10];
    int tamañocola = 0;
    DefaultListModel<String> model = new DefaultListModel<>();
    public frmCola() {
        initComponents();
        lstcola.setModel(model);        
        for (int i = 0; i < 10; i++) {
            Cola[i]="";
        }
        mostrarcola();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltampila = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstcola = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txtvalorcola = new javax.swing.JTextField();
        btnEncolar = new javax.swing.JButton();
        lblultimocola = new javax.swing.JLabel();
        btndesacolar = new javax.swing.JButton();
        btnvaciarcola = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cola con Arreglo");

        lbltampila.setText("Tamaño Cola:");

        lstcola.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lstcola.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstcola);

        jLabel1.setText("Insertar:");

        txtvalorcola.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtvalorcola.setText("_");

        btnEncolar.setText("Encolar");
        btnEncolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncolarActionPerformed(evt);
            }
        });

        lblultimocola.setText("Ultimo ingresar:");

        btndesacolar.setText("Desacolar");
        btndesacolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndesacolarActionPerformed(evt);
            }
        });

        btnvaciarcola.setText("Vaciar Cola");
        btnvaciarcola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvaciarcolaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("FIFO ( PRIMERO EN ENTRAR - PRIMERO EN SALIR )");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblultimocola)
                                    .addComponent(lbltampila)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtvalorcola, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnvaciarcola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btndesacolar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEncolar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtvalorcola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEncolar))
                        .addGap(18, 18, 18)
                        .addComponent(btndesacolar)
                        .addGap(26, 26, 26)
                        .addComponent(btnvaciarcola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(lbltampila)
                        .addGap(84, 84, 84)
                        .addComponent(lblultimocola))
                    .addComponent(jScrollPane1))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void mostrarcola(){
        model.clear();
        for (int i = 0; i < 10; i++) {
            model.addElement((10-i-1)+"=> "+Cola[10-i-1]);
        }
        lbltampila.setText("Tamaño Cola:" + tamañocola);
        lblultimocola.setText("Ultimo ingresar:"+Cola[0]);
    }
    private void btnEncolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncolarActionPerformed
        if(tamañocola<10){
            for (int i = tamañocola; i >0 ; i--) {
                Cola[i]=Cola[i-1];
            }
            Cola[0] = txtvalorcola.getText().trim();
            tamañocola++;
            mostrarcola();
        }
    }//GEN-LAST:event_btnEncolarActionPerformed

    private void btndesacolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndesacolarActionPerformed
        if(tamañocola>0){
            Cola[--tamañocola] = "";
            mostrarcola();
        }
    }//GEN-LAST:event_btndesacolarActionPerformed

    private void btnvaciarcolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaciarcolaActionPerformed
        for (int i = 0; i < 10; i++) {
            Cola[i]="";
        }
        tamañocola = 0;
        mostrarcola();
    }//GEN-LAST:event_btnvaciarcolaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncolar;
    private javax.swing.JButton btndesacolar;
    private javax.swing.JButton btnvaciarcola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltampila;
    private javax.swing.JLabel lblultimocola;
    private javax.swing.JList<String> lstcola;
    private javax.swing.JTextField txtvalorcola;
    // End of variables declaration//GEN-END:variables
}
