/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pilacolalista;

import javax.swing.DefaultListModel;

/**
 *
 * @author PCPCPC
 */
public class frmLista extends javax.swing.JInternalFrame {

    String Lista[] = new String[10];
    int tamañolista = 0;
    DefaultListModel<String> model = new DefaultListModel<>();
    public frmLista() {
        initComponents();
        lstlista.setModel(model);        
        for (int i = 0; i < 10; i++) {
            Lista[i]="";
        }
        mostrarlista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnvaciarlista = new javax.swing.JButton();
        lbltampila = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstlista = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txtvalorlista = new javax.swing.JTextField();
        btnEnlistar = new javax.swing.JButton();
        lblultimolista = new javax.swing.JLabel();
        btndeslistar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtposicion = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Lista con Arreglo");

        btnvaciarlista.setText("Vaciar Lista");
        btnvaciarlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvaciarlistaActionPerformed(evt);
            }
        });

        lbltampila.setText("Tamaño Lista:");

        lstlista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lstlista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstlista);

        jLabel1.setText("Insertar:");

        txtvalorlista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtvalorlista.setText("_");

        btnEnlistar.setText("Enlistar");
        btnEnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnlistarActionPerformed(evt);
            }
        });

        lblultimolista.setText("Ultimo ingresar:");

        btndeslistar.setText("Deslistar");
        btndeslistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeslistarActionPerformed(evt);
            }
        });

        jLabel2.setText("Posicion:");

        txtposicion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtposicion.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblultimolista)
                            .addComponent(lbltampila)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtvalorlista, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(txtposicion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnvaciarlista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndeslistar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEnlistar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtvalorlista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtposicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnlistar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndeslistar)
                        .addGap(26, 26, 26)
                        .addComponent(btnvaciarlista)
                        .addGap(25, 25, 25)
                        .addComponent(lbltampila)
                        .addGap(84, 84, 84)
                        .addComponent(lblultimolista))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void mostrarlista(){
        model.clear();
        for (int i = 0; i < 10; i++) {
            model.addElement((10-i-1)+"=> "+Lista[10-i-1]);
        }
        lbltampila.setText("Tamaño Lista:" + tamañolista);
        lblultimolista.setText("Ultimo ingresar:"+Lista[Integer.parseInt(txtposicion.getText().trim())]);
    }
    private void btnvaciarlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaciarlistaActionPerformed
        for (int i = 0; i < 10; i++) {
            Lista[i]="";
        }
        tamañolista = 0;
        mostrarlista();
    }//GEN-LAST:event_btnvaciarlistaActionPerformed

    private void btnEnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnlistarActionPerformed
        if(tamañolista<10){            
            int posicion = Integer.parseInt(txtposicion.getText().trim());
            if(posicion>=0 && posicion<10){
                Lista[posicion] = txtvalorlista.getText().trim();
                tamañolista++;
                mostrarlista();
            }
        }
    }//GEN-LAST:event_btnEnlistarActionPerformed

    private void btndeslistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeslistarActionPerformed
        if(tamañolista>0){
            int posicion = Integer.parseInt(txtposicion.getText().trim());
            if(posicion>=0 && posicion<10){
                Lista[posicion] = "";
                --tamañolista;
                mostrarlista();}
        }
    }//GEN-LAST:event_btndeslistarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnlistar;
    private javax.swing.JButton btndeslistar;
    private javax.swing.JButton btnvaciarlista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltampila;
    private javax.swing.JLabel lblultimolista;
    private javax.swing.JList<String> lstlista;
    private javax.swing.JTextField txtposicion;
    private javax.swing.JTextField txtvalorlista;
    // End of variables declaration//GEN-END:variables
}
