package pilacolalista;

import javax.swing.DefaultListModel;

public class frmPila extends javax.swing.JInternalFrame {
    String Pila[] = new String[10];
    int tamañopila = 0;
    DefaultListModel<String> model = new DefaultListModel<>();
    
    public frmPila() {
        initComponents();
        lstpila.setModel(model);        
        for (int i = 0; i < 10; i++) {
            Pila[i]="";
        }
        mostrarpila();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstpila = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txtvalorpila = new javax.swing.JTextField();
        btnEmpilar = new javax.swing.JButton();
        lblultimopila = new javax.swing.JLabel();
        btndesapilar = new javax.swing.JButton();
        btnvaciarpila = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbltampila = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Pila con Arreglo");

        lstpila.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lstpila.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstpila);

        jLabel1.setText("Insertar:");

        txtvalorpila.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtvalorpila.setText("_");

        btnEmpilar.setText("Emplilar");
        btnEmpilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpilarActionPerformed(evt);
            }
        });

        lblultimopila.setText("Ultimo ingresar:");

        btndesapilar.setText("Desapilar");
        btndesapilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndesapilarActionPerformed(evt);
            }
        });

        btnvaciarpila.setText("Vaciar Pila");
        btnvaciarpila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvaciarpilaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("LIFO ( ULTIMO EN ENTRAR - PRIMERO EN SALIR )");

        lbltampila.setText("Tamaño Pila:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblultimopila)
                                    .addComponent(lbltampila)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtvalorpila, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnvaciarpila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btndesapilar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEmpilar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtvalorpila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEmpilar))
                        .addGap(18, 18, 18)
                        .addComponent(btndesapilar)
                        .addGap(26, 26, 26)
                        .addComponent(btnvaciarpila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(lbltampila)
                        .addGap(84, 84, 84)
                        .addComponent(lblultimopila))
                    .addComponent(jScrollPane1))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void mostrarpila(){
        model.clear();
        for (int i = 0; i < 10; i++) {
            model.addElement((10-i-1)+"=> "+Pila[10-i-1]);
        }
        lbltampila.setText("Tamaño Pila:" + tamañopila);
        lblultimopila.setText("Ultimo ingresar:"+Pila[(tamañopila==0?1:tamañopila)-1]);
    }
    private void btnEmpilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpilarActionPerformed
        if(tamañopila<10){
            Pila[tamañopila++] = txtvalorpila.getText().trim();
            mostrarpila();
        }
    }//GEN-LAST:event_btnEmpilarActionPerformed

    private void btndesapilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndesapilarActionPerformed
        if(tamañopila>0){
            Pila[--tamañopila] = "";
            mostrarpila();
        }
    }//GEN-LAST:event_btndesapilarActionPerformed

    private void btnvaciarpilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaciarpilaActionPerformed
        for (int i = 0; i < 10; i++) {
            Pila[i]="";
        }
        tamañopila = 0;
        mostrarpila();
    }//GEN-LAST:event_btnvaciarpilaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpilar;
    private javax.swing.JButton btndesapilar;
    private javax.swing.JButton btnvaciarpila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltampila;
    private javax.swing.JLabel lblultimopila;
    private javax.swing.JList<String> lstpila;
    private javax.swing.JTextField txtvalorpila;
    // End of variables declaration//GEN-END:variables
}
